config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :payments
  resources :replies
  get 'comments/create'
  get 'course/assesment'
  get 'welcome/index'
  get 'exam/assesment'
  get 'users/index'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    # Add this
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, :only =>[:show]
resources :courses do
  resources :comments
end
  
  # devise_for :users
  root to: "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_many:replies
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action:authenticate_user!
before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @course=Course.find(params[:course_id])
    @comments = @course.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @course=Course.find(params[:course_id])
    @comment = @course.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to courses_url, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: courses_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :course_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@course, @course.comments.build]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
  <%  if user_signed_in? %>
  <%= form.text_field :user_id, value: current_user.id%>
  <%end%>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<div class="col-lg-4 col-md-6">
<div class="card">
<li class="list-group-item d-flex justify-content-between align-items-center">
Cras justo odio
<span class="badge badge-primary badge-pill">14</span>
</li>
</div>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions and Answers</h1>

<br>
<% @comments.each do |comment| %>
<div class="col-lg-4 col-md-6">
<div class="card">
<li class="list-group-item d-flex justify-content-between align-items-center">
<%= comment.content %>
<td><%= link_to 'Edit', [comment.course, comment], method: :edit%></td>
        <td><%= link_to 'Delete', [comment.course, comment], method: :delete, data: { confirm: 'Are you sure?' }%></td>
<%if current_user.id==comment.user_id %>
<span class="badge badge-primary badge-pill"><%= link_to 'reply', new_reply_path(:comment_id => comment.id), :"data-no-turbolink" => true, method: "get"  %></span>
<%end%>
</li>
</div>
</div>
<div class="col-lg-4 col-md-6"></br>

    <!--Card Primary-->
    
    
      <div class="card-body">
        <% comment.replies.each do |reply| %>
        <h5 class="font-weight-bold amber-text mt-2 mb-3"><%=reply.content%><i class="far fa-heart ml-3"></i></h5>
        
          <%end%></p>
      </div>
    <!--/.Card Primary-->

  </div></br>
<% end %>
<%= link_to 'New Question', new_course_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', course_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @comment.course_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>