config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :payments
  resources :replies
  get 'comments/create'
  get 'course/assesment'
  get 'welcome/index'
  get 'exam/assesment'
  get 'users/index'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    # Add this
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, :only =>[:show]
resources :courses do
  resources :comments
end
  
  # devise_for :users
  root to: "welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  
  # before_action :only_admin, only: [:edit, :new]

  # before_action :only_admin, only: [:edit, :new]
  

  # GET /courses
  # GET /courses.json
  def index
    @currentUser = current_user.id
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
   @comment = Comment.all
  end

  # GET /courses/new
  def new
    @course = current_user.courses.build
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = current_user.courses.build(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
   
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    @course = Course.find(params[:id])
    
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
  def course_params
    params.require(:course).permit(:image, :image_cache)
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:image, :title, :credit_number, :content, :upload_file, :course_price, :status, :marks, :attemption, :user_id ,{file: []})
    end

    def only_admin
      unless current_user.user_role == 'instructor'
         redirect_to courses_url, notice: 'you are not allowed to access this page.' 
      end
    end

    def only_admin
      unless current_user.user_role == 'instructor'
         redirect_to courses_url, notice: 'you are not allowed to access this page.' 
      end
    end
    def uploadFile
      course = Course.save(params[:upload])
      render :text => "File has been uploaded successfully"
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="container", style="background-color: whitesmoke;">
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :credit_number %>
    <%= form.text_field :credit_number, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :upload_file %>
    <%= form.file_field :upload_file, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :course_price %>
    <%= form.text_field :course_price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.text_field :status, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :marks %>
    <%= form.text_field :marks, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :attemption %>
    <%= form.text_field :attemption, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.hidden_field :user_id, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<style>
  .card-img-top{

  }
</style>

<%= link_to 'Edit', edit_course_path(@course) %> 
<%= link_to 'Back', courses_path %>

<div style="background:whitesmoke;width:100%">
<div class="card p-5" style='width:70%;margin:auto'>
<!-- Card content -->
<div class="card-body">

  <!-- Title -->
  <h3 class="card-title"><b><%=@course.title%>&nbsp;/&nbsp;<%=@course.credit_number%> &nbsp;Credits</b></h3>
  <!-- Text -->
  <div class="A" style="background:yellow">
    <div style="width:50%;float:left;border-right:1px solid whitesmoke">
      <h5 class="card-text">Instructor:</p>
      <p class="card-text"><%=@course.user.email%></p>
    </div>
    <div style="width:50%;float:right;padding-left:30px">
      <!-- Button -->
      <p class="card-text" style="color:green;font-weight:bolder;font-size:20px"><%=@course.course_price %> RWF</p>
      <%= link_to 'Take Course', new_payment_path, class:"btn btn-success", style:"border-radius:5px" %>
    </div>
  </div>
</div>
  <!-- Card image -->
  <div class="view overlay">
      <%if @course.image.url%>
        <%= image_tag @course.image.url, class:"card-img-top",alt:"Card image cap"%>
      <% end%>
    <a href="#!">
      <div class="mask rgba-white-slight">salute</div>
    </a>
  </div>

  <!-- Card content -->
  <div class="card-body">

    <!-- Title -->
    <h4 class="card-title">Course Description</h4>
    <!-- Text -->
    <p class="card-text"><%=@course.content%></p>
    <!-- Button -->

  <buton class="btn btn-lg">
  <strong>Status:</strong>
  <%= @course.status %>
</p>

<p>
  <strong>Marks:</strong>
  <%= @course.marks %>
</p>

<p>
  <strong>Attemption:</strong>
  <%= @course.attemption %>
</p>

<p><%= link_to "Download", @course.upload_file_url %></p>
<a href="/exam/assesment">Assesment</a>
</button>
  </div>
  <%if current_user.user_role=='instructor'%>
  <%= link_to 'Edit', edit_course_path(@course), class:'btn btn-sm' %>
  <a href="/exam/assesment">Assesment</a>
  <%end%>
</div>
</div>
<!-- Card -->


<p>
  <strong>User:</strong>
  <%= @course.user_id %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> 
<%= link_to 'Back', courses_path %><br>
<a href="/exam/assesment">Assesment</a>